logging:
  level:
    com.teoresi.argo: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

  file:
    name: logs/logfile_tmp.log
    rolling-file-name: logs/logfile-{yyyy-MM-dd}.log
    max-size: 512MB
    total-size-cap: 10GB
    clean-history-on-start: false


spring:
  datasource:
    url: jdbc:mysql://192.168.126.35:3307/db
    username: root
    password: ENC(Cz8qHY/yTW/2PAISSsylwVWO6fH+kHE+cDUzq+qJScQnRYEqUKetwP+fEm7ubRQHUDtV9LhA8Wr+y3+jpAcRig==)

    jpa:
    properties:
      hibernate:
        ddl :
          auto : validate
          format_sql: true

  flyway:
    enabled: false
    baselineOnMigrate: true
    validateOnMigrate: true
    locations:
      - classpath:mysql/schema
      - classpath:mysql/prod-data

application:
  cors:
    allowedOrigins: 'http://localhost:4200'
    #allowedOrigins: 'https://192.168.126.35'