server:
  port: 8080
  error:
    include-message: always

jasypt:
  encryptor:
    password: 51kqFFT4Gmac2TSWT8k51Q

spring:
  application:
    name: @project.name@
    version: @project.version@

  mail:
    host: smtp.gmail.com
    port: 587
    username: smtpmail587sender@gmail.com
    password: ENC(486o42WzBDVoPxAL9SNlEk79EerQXxwIcloTraocr/FYbO4gQ0HEmDieYwgbqQbO8hPQ6w5auXFddtq1bhR17g==)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: true
    time-zone: UTC
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Rome

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
    jwt:
      secretKey: ENC(gN+XcNwye0GV5CQjnKRAJAmce/+wNUahuPlBjB4GvlKMjWehW084QCt9qW6KFSvqhgkqlEH1dw9rZ7H1HIiERA==)
      cryptoKey: ENC(DnEMgOMxAvci3GmBVCh3DdyTP1Bp+h7d5gJjQU2y+06Lue5FlnatRo6L+g5IMluFiIHvlQHQmaE8QOkNnAXgIg==)

      tokenDurationMs: 1800000
      tokenRenewBeforeExpirationMs: 1800000
