version: '3.8'  # oppure rimuovilo del tutto come suggerito nel warning

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invest_ai
      MYSQL_USER: invest_user
      MYSQL_PASSWORD: invest_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - invest_ai_network

volumes:
  db_data:

networks:
  invest_ai_network:  # ✅ definizione della rete
    driver: bridge
